# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    
    # sast scan
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
       name: bandit-findings
       path: bandit-report.json

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pwnewregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d8b1b90318444a6490ba5f9ea0394f0a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5b5b8c8c34ff4e8ea45b9065cd49cef9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: pwnewregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d8b1b90318444a6490ba5f9ea0394f0a }}/mltest:${{ github.sha }}
        file: ./Dockerfile
        
    - name: Docker Scout Scan
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh
        echo ${{ secrets.AZURE_REPO_PWD }} | docker login -u ${{ secrets.AZURE_REPO_USER }} --password-stdin
        docker scout quickview
        docker scout cves

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentperformanceapp'
        #slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_120890d369d84d7aafaeca48ac8881b4 }}
        images: 'pwnewregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d8b1b90318444a6490ba5f9ea0394f0a }}/mltest:${{ github.sha }}'
